from intelligence.report import MarketReport
from intelligence.generator import ReportGenerator
from analysis.signal import Signal


def test_phoenix_intelligence_flow():

    # 1. Signal generated by analysis layer
    signal = Signal(
        symbol="BTCUSDT",
        action="BUY",
        confidence=78,
        reasons=[
            "Price above MA",
            "MACD positive"
        ]
    )

    # 2. Intelligence layer creates market report
    report = MarketReport(
        symbol=signal.symbol,
        timeframe="4H",
        trend="BULLISH",
        regime="TRENDING_BULLISH",
        signal=signal.action,
        confidence=signal.confidence,
        risk="MEDIUM",
        reasons=signal.reasons
    )

    # 3. Report generator produces human output
    generator = ReportGenerator()

    output = generator.generate(report)

    # 4. Validate Phoenix final intelligence output
    assert "PHOENIX MARKET REPORT" in output
    assert "BTCUSDT" in output
    assert "BUY" in output
    assert "78%" in output
    assert "MACD positive" in output